services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  library:
    build: ./library
    container_name: library
    depends_on:
      - db
    ports:
      - "8080:8000"
